<?php /* @var $block \Amasty\GiftCardAccount\Block\Customer\Cards */ ?>

<div class="amcardacc-codes-block" data-bind="scope: 'amcard-account-render'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<div class="amcardacc-template-container" data-amcardacc-js="template" data-bind="scope: 'amcard-giftcards'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-amcardacc-js='template']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>
