<?php /** @var $block \Amasty\GiftCardAccount\Block\Checkout\Cart\GiftCard */ ?>
<div data-amcardacc-js="template" data-bind="scope: 'amcard-giftcards'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-amcardacc-js='template']": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "amcard-giftcards": {
                        "component": "Amasty_GiftCardAccount/js/view/payment/paypal",
                        "template": "Amasty_GiftCardAccount/payment/paypal-giftcard",
                        "codes": <?= /** @noEscape */ $block->getAppliedCodes() ?>,
                        "isGiftCardEnable": "<?= $block->escapeHtmlAttr($block->isEnableGiftFormInCart()) ?>",
                        "deleteCardUrl": "<?= $block->escapeUrl($block->getUrl('amgcard/cart/remove')) ?>",
                        "addCardUrl": "<?= $block->escapeUrl($block->getUrl('amgcard/cart/apply')) ?>",
                        "checkCardUrl": "<?= $block->escapeUrl($block->getUrl('amgcard/cart/check')) ?>",
                        "children": {
                            "errors": {
                                "component": "Amasty_GiftCardAccount/js/view/payment/gift-card-messages",
                                "displayArea": "messages"
                            }
                        }
                    },
                    "amcard-cart-render": {
                        "component": "Amasty_GiftCardAccount/js/view/account/codes",
                        "template": "Amasty_GiftCardAccount/account/codes"
                    }
                }
            }
        }
    }
</script>
